[project]
name = "chembl-api-demo"
version = "0.1.0"
description = "A demo for using the ChEMBL API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chembl-webresource-client>=0.10.9",
]
